version: "3"

services:
  gateway-service:
    build:
      context: ./
      dockerfile: ./gateway-service/gateway-service.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
